ECOMMERCE/ECOMMERCE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
]

ECOMMERCE/core/urls.py
from django.urls import path
from .views import HomeView, ItemDetailView, checkout, add_to_cart, remove_from_cart, OrderSummaryView, remove_single_item_from_cart

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='item-list'),
    path('checkout/', checkout, name='checkout'),
    path('order-summary', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>', remove_single_item_from_cart, name='remove-single-item-from-cart'),
]

ECOMMERCE/core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport Wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

# Create your models here.
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug':self.slug
            })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug':self.slug
            })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug':self.slug
            })
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, blank=True, null=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

ECOMMERCE/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View
from .models import Item, OrderItem, Order
from django.utils import timezone
from django.contrib import messages
# Create your views here.

def checkout(request):
    return render(request, "checkout.html")

def products(request):
    return render(request, "products.html")

class HomeView(ListView):
    model = Item
    paginate_by = 1
    template_name = "home.html"

class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object':order
            }
            return render(self.request, "order_summary.html", context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have active order")
            return redirect("/")

class ItemDetailView(DetailView):
    model = Item
    template_name = "product.html"

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(user=request.user, 
        item=item, 
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity is updated")
            return redirect("core:order-summary")
        else:
            order.items.add(order_item)
            messages.info(request, "This item is added to your cart")
            return redirect("core:order-summary")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, "This item is added to your cart")
        return redirect("core:order-summary")

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item = item,
                user = request.user,
                ordered = False
            )[0]
            order.items.remove(order_item)
            messages.info(request, "This item is removed from your cart")
            return redirect("core:order-summary")
        else:
            messages.info(request, "This item is not in your cart")
            return redirect("core:product", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("core:product", slug=slug)

@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item = item,
                user = request.user,
                ordered = False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, "This item quantity is updated")
                return redirect("core:order-summary")
            else:
                order_item.quantity = 1
                order.items.remove(order_item)
                messages.info(request, "This item  is removed from your cart")
                return redirect("core:order-summary")
        else:
            messages.info(request, "This item is not in your cart")
            return redirect("core:order-summary")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("core:order-summary") 

ECOMMERCE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block head_title %}{% endblock %}</title>
        {% block extra_head %}
        {% endblock %}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
        <style type="text/css">
          html,
          body,
          header,
          .carousel {
            height: 60vh;
          }
      
          @media (max-width: 740px) {
      
            html,
            body,
            header,
            .carousel {
              height: 100vh;
            }
          }
      
          @media (min-width: 800px) and (max-width: 850px) {
      
            html,
            body,
            header,
            .carousel {
              height: 100vh;
            }
          }
      
        </style>
    </head>
<body>
    {% include "navbar.html" %}
    <div class="mt-5 pt-4">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            {% endfor %}
        {% endif %}
    </div>
    {% block content %}
    {% endblock content%}

    {% block extra_body %}
    {% endblock extra_body %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

ECOMMERCE/templates/checkout.html
{% extends "base.html" %}
{% block content %}
  <body class="grey lighten-3">
    <!--Main layout-->
    <main>
      <div class="container wow fadeIn">

        <!-- Heading -->
        <h2 class="my-5 h2 text-center">Checkout form</h2>

        <!--Grid row-->
        <div class="row">

          <!--Grid column-->
          <div class="col-md-8 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card content-->
              <form class="card-body">


                <!--address-->
                <div class="md-form mb-5">
                  <input type="text" id="address" class="form-control" placeholder="1234 Main St">
                  <label for="address" class="">Address</label>
                </div>

                <!--address-2-->
                <div class="md-form mb-5">
                  <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">
                  <label for="address-2" class="">Address 2 (optional)</label>
                </div>

                <!--Grid row-->
                <div class="row">

                  <!--Grid column-->
                  <div class="col-lg-4 col-md-12 mb-4">

                    <label for="country">Country</label>
                    <select class="custom-select d-block w-100" id="country" required>
                      <option value="">Choose...</option>
                      <option>United States</option>
                    </select>
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>

                  </div>
                  <!--Grid column-->

                  <!--Grid column-->
                  <div class="col-lg-4 col-md-6 mb-4">

                    <label for="zip">Zip</label>
                    <input type="text" class="form-control" id="zip" placeholder="" required>
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>

                  </div>
                  <!--Grid column-->

                </div>
                <!--Grid row-->

                <hr>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="same-address">
                  <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="save-info">
                  <label class="custom-control-label" for="save-info">Save this information for next time</label>
                </div>

                <hr>

                <div class="d-block my-3">
                  <div class="custom-control custom-radio">
                    <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
                    <label class="custom-control-label" for="credit">Stripe</label>
                  </div>
                  <div class="custom-control custom-radio">
                    <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                    <label class="custom-control-label" for="paypal">Paypal</label>
                  </div>
                </div>
                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

              </form>

            </div>
            <!--/.Card-->

          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-4 mb-4">

            <!-- Heading -->
            <h4 class="d-flex justify-content-between align-items-center mb-3">
              <span class="text-muted">Your cart</span>
              <span class="badge badge-secondary badge-pill">3</span>
            </h4>

            <!-- Cart -->
            <ul class="list-group mb-3 z-depth-1">
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Product name</h6>
                  <small class="text-muted">Brief description</small>
                </div>
                <span class="text-muted">$12</span>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Second product</h6>
                  <small class="text-muted">Brief description</small>
                </div>
                <span class="text-muted">$8</span>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Third item</h6>
                  <small class="text-muted">Brief description</small>
                </div>
                <span class="text-muted">$5</span>
              </li>
              <li class="list-group-item d-flex justify-content-between bg-light">
                <div class="text-success">
                  <h6 class="my-0">Promo code</h6>
                  <small>EXAMPLECODE</small>
                </div>
                <span class="text-success">-$5</span>
              </li>
              <li class="list-group-item d-flex justify-content-between">
                <span>Total (USD)</span>
                <strong>$20</strong>
              </li>
            </ul>
            <!-- Cart -->

            <!-- Promo code -->
            <form class="card p-2">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
                </div>
              </div>
            </form>
            <!-- Promo code -->

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </div>
    </main>
    <!--Main layout-->
  </body>
{% endblock content %}

ECOMMERCE/templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
        role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

ECOMMERCE/templates/home.html
{% extends "base.html" %}

{% block content %}
  <body>
    <!--Main layout-->
    <main>
      <div class="container">

        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

          <!-- Navbar brand -->
          <span class="navbar-brand">Categories:</span>

          <!-- Collapse button -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Collapsible content -->
          <div class="collapse navbar-collapse" id="basicExampleNav">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">All
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Shirts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Sport wears</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Outwears</a>
              </li>

            </ul>
            <!-- Links -->

            <form class="form-inline">
              <div class="md-form my-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
              </div>
            </form>
          </div>
          <!-- Collapsible content -->

        </nav>
        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">

          <!--Grid row-->
          <div class="row wow fadeIn">
            {% for item in object_list %}
              <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4">

                <!--Card-->
                <div class="card">

                  <!--Card image-->
                  <div class="view overlay">
                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                      alt="">
                    <a href="{{item.get_absolute_url}}">
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>
                  <!--Card image-->

                  <!--Card content-->
                  <div class="card-body text-center">
                    <!--Category & Title-->
                    <a href="{{item.get_absolute_url}}" class="grey-text">
                      <h5>{{item.get_category_display}}</h5>
                    </a>
                    <h5>
                      <strong>
                        <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{item.title}}
                          <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                        </a>
                      </strong>
                    </h5>

                    <h4 class="font-weight-bold blue-text">
                      {% if item.discount_price %}
                        <strong>${{item.discount_price}}</strong>
                      {% else %}
                        <strong>${{item.price}}</strong>
                      {% endif %}
                    </h4>

                  </div>
                  <!--Card content-->

                </div>
                <!--Card-->

              </div>
              <!--Grid column-->
            {% endfor %}
          </div>
          <!--Grid row-->

        </section>
        <!--Section: Products v.3-->
        {% if is_paginated %}
        <!--Pagination-->
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            <!--Arrow left-->
            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {% endif %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{page_obj.number}}
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
        <!--Pagination-->
        {% endif %}
      </div>
    </main>
    <!--Main layout-->

  </body>
{% endblock content %}

ECOMMERCE/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <body>
    <!--Main layout-->
    <main>
      <div class="container">
        <div class="table-responsive text-nowrap">
            <h3>Order Summary</h3>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Item Title</th>
                  <th scope="col">Price</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Total Price</th>
                </tr>
              </thead>
              <tbody>
                  {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{order_item.item.title}}</td>
                        <td>{{order_item.item.price}}</td>
                        <td>
                          <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                          {{order_item.quantity}}
                          <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                        </td>
                        {% if order_item.item.discount_price %}
                        <td>
                            {{ order_item.get_total_discount_item_price }}
                            <span class="badge badge-primary">Saving {{ order_item.get_amount_saved }}</span>
                        </td>

                        {% else %}
                        <td>{{ order_item.get_total_item_price }}</td>
                        {% endif %}
                        <td>
                          <a style='color:red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                  {% empty %}
                    <tr>  
                      <td colspan="5"><strong>Your cart is empty</strong></td>
                    </tr>
                    <tr>
                      <td colspan="5">
                        <a class="btn btn-primary float-right" href="/">CONTINUE SHOPPING</a>
                      </td>
                    </tr>
                  {% endfor %}
                  {% if object.get_total %}
                    <tr>
                      <td colspan="4"><strong>Order Total</strong></td>
                      <td><strong>{{ object.get_total }}</strong></td>
                    </tr>
                    <tr>
                      <td colspan="5">
                        <a class="btn btn-warning float-right ml-2" href="/checkout">PROCEED TO CHECKOUT</a>
                        <a class="btn btn-primary float-right" href="/">CONTINUE SHOPPING</a>
                      </td>
                    </tr>
                  {% endif %}
              </tbody>
            </table>
          
          </div>
      </div>
    </main>
    <!--Main layout-->

  </body>
{% endblock content %}

ECOMMERCE/templates/product.html
{% extends "base.html" %}
{% block content %}
  <body>
    <!--Main layout-->
    <main class="mt-5 pt-4">
      <div class="container dark-grey-text mt-5">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4">

            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6 mb-4">

            <!--Content-->
            <div class="p-4">

              <div class="mb-3">
                <a href="">
                  <span class="badge purple mr-1">{{object.get_category_display}}</span>
                </a>
                <a href="">
                  <span class="badge blue mr-1">New</span>
                </a>
                <a href="">
                  <span class="badge red mr-1">Bestseller</span>
                </a>
              </div>

              <p class="lead">
                {% if item.discount_price %}
                  <span class="mr-1">
                    <del>${{item.price}}</del>
                  </span>
                  <span>${{item.discount_price}}</span>
                {% else %}
                  <span>${{item.price}}</span>
                {% endif %}
              </p>

              <p class="lead font-weight-bold">{{object.description}}</p>

              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa
                sint voluptatibus!
                Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.</p>

              {% comment %} <form class="d-flex justify-content-left">
                <!-- Default input -->
                <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
                <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>

              </form> {% endcomment %}
              <a href="{{object.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p">Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </a>
              
              <a href="{{object.get_remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p">Remove from cart
                </a>

            </div>
            <!--Content-->

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

        <hr>

        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 text-center">

            <h4 class="my-4 h4">Additional information</h4>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
              voluptates,
              quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4">

            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">

            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">

            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

      </div>
    </main>
    <!--Main layout-->
  </body>
{% endblock content %}

ECOMMERCE/templates/scripts.html
{% load static %}

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
// Animations initialization
new WOW().init();

</script>